---
- name: Check if node_exporter is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/node_exporter"
  register: node_exporter_binary

- include: install.yml
  when: not node_exporter_binary.stat.exists or node_exporter_force_install

- import_tasks: configure.yml
  tags:
    - node_exporter.configure

- name: Ensure Node Exporter is enabled on boot
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
